####################
# SERVER           #
####################

# whether to enable debug logs
DEBUG: true

TEST_KEEP_DB: false

DOCS_URL_PREFIX: /audit

# defaults to "http://arborist-service/"
ARBORIST_URL:

# If `PULL_FROM_QUEUE` is true, `QUEUE_CONFIG` is required.
# `QUEUE_CONFIG.type` is one of: [aws_sqs].
# - if type == api: logs are created by hitting the log creation endpoint.
# - if type == aws_sqs: logs are pulled from an SQS and fields `sqs_url` and
# `region` are required. Fields `aws_access_key_id` and
# `aws_secret_access_key` are optional.
PULL_FROM_QUEUE: true
QUEUE_CONFIG:
  type: aws_sqs
  sqs_url:
  region:
  aws_access_key_id:
  aws_secret_access_key:
# how often to check the queue for new audit logs after
# seeing an empty queue
PULL_FREQUENCY_SECONDS: 1  # TODO less frequent

####################
# DATABASE         #
####################

DB_DRIVER: postgresql
DB_HOST:
DB_PORT:
DB_USER:
DB_PASSWORD:
DB_DATABASE: audit

DB_POOL_MIN_SIZE: 1
DB_POOL_MAX_SIZE: 16
DB_ECHO: False
DB_SSL:
DB_USE_CONNECTION_FOR_REQUEST: true
DB_RETRY_LIMIT: 1
DB_RETRY_INTERVAL: 1

####################
# API              #
####################

# if left empty, queries are not time-boxed
QUERY_TIMEBOX_MAX_DAYS:

QUERY_PAGE_SIZE: 1000

# whether to return usernames in query responses,
# and to allow querying by username
QUERY_USERNAMES: true
