####################
# SERVER           #
####################

# whether to enable debug logs
DEBUG: true

TEST_KEEP_DB: false

DOCS_URL_PREFIX: /audit

# defaults to "http://arborist-service/"
ARBORIST_URL:

####################
# DATABASE         #
####################

DB_DRIVER: postgresql
DB_HOST:
DB_PORT:
DB_USER:
DB_PASSWORD:
DB_DATABASE: audit

DB_POOL_MIN_SIZE: 1
DB_POOL_MAX_SIZE: 16
DB_ECHO: False
DB_SSL:
DB_USE_CONNECTION_FOR_REQUEST: true
DB_RETRY_LIMIT: 1
DB_RETRY_INTERVAL: 1

####################
# API              #
####################

QUERY_TIMEBOX_MAX_DAYS: 30
QUERY_PAGE_SIZE: 100

# whether to return usernames in query responses,
# and to allow querying by username
QUERY_USERNAMES: true
